Repository TeamPickle/covid19-v3, pull requests merged in 2021-11, with the labels that each got.

#17 fix: python version 2 -> 3
  Dockerfile
Labels: size/XS

#15 fix(docker): timezone
  Dockerfile
Labels: size/XS

#25 chore: prettier eslint integration
  .eslintrc.js
  package.json
  yarn.lock
Labels: size/M

#26 feat: use openapi
  config.schema.json
  package.json
  src/bot/commands/commands/graph.ts
  src/bot/commands/commands/status.ts
  src/bot/models/graphModel.ts
  src/bot/util/graph.ts
  yarn.lock
Labels: size/XL

#16 feat(ci): add github deploy action
  .env.example
  .github/workflows/pull_request.yml
  .github/workflows/push.yml
  .gitignore
  Dockerfile
  README.md
  config.schema.json
  package.json
  src/bot/commands/commands/status.ts
  src/bot/index.ts
  src/config.ts
  src/index.ts
  src/web/app.ts
  yarn.lock
Labels: size/L

#28 refactor: remove cron
  src/bot/index.ts
  src/bot/tasks/index.ts
  src/bot/util/send.ts
Labels: size/M

#27 feat: vaccine
  src/bot/commands/commands/vaccine.ts
Labels: size/M
